language: node_js
node_js:
  - "7"

install:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install -g jshint
  - npm install -g codecov
  - npm install -g istanbul
  - npm install
  - bower install

script:
  - grunt lint
